services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src  # For hot reload
    environment:
      - MODEL_PATH=/models
      - PYTHONUNBUFFERED=1
      - WANDB_API_KEY=${WANDB_API_KEY}

  train:
    build:
      context: .
      dockerfile: Dockerfile
      target: train
    volumes:
      - ./data:/data
      - ./models:/models
    environment:
      - MODEL_PATH=/models
      - DATA_PATH=/data

  evaluate:
    build:
      context: .
      dockerfile: Dockerfile
      target: evaluate
    volumes:
      - ./data:/data
      - ./models:/models
    environment:
      - MODEL_PATH=/models
      - DATA_PATH=/data
      - WANDB_API_KEY=${WANDB_API_KEY}

  infer:
    build:
      context: .
      dockerfile: Dockerfile
      target: infer
    volumes:
      - ./data:/data
      - ./models:/models
    environment:
      - MODEL_PATH=/models
      - DATA_PATH=/data
      - WANDB_API_KEY=${WANDB_API_KEY}
