defaults:
  - _self_
  - model: dssm

hydra:
  run:
    dir: ${paths.output_dir}/train_runs/${now:%Y-%m-%d}_${now:%H-%M-%S}_split${data.splits}_bs${training.batch_size}
  sweep:
    dir: ${paths.output_dir}/train_multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: run_${hydra.job.num}_split${data.splits}_bs${training.batch_size}

paths:
  root_dir: ${hydra:runtime.cwd}
  data_dir: ${paths.root_dir}/data/processed
  model_dir: ${paths.root_dir}/models
  output_dir: ${paths.root_dir}/outputs

data:
  base_dir: ${paths.data_dir}
  splits: [1]  # If null, uses all splits (1-5). Can specify list like [1, 2, 3]

training:
  max_epochs: 5
  batch_size: 64
  learning_rate: 0.0001
  class_weights: [1.0, 7.143]
  use_gpu: true
  checkpoint_dir: ${paths.model_dir}
  patience: 10
