name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker build -t train:latest . -f dockerfiles/train.dockerfile
          docker build -t evaluate:latest . -f dockerfiles/evaluate.dockerfile
          docker build -t infer:latest . -f dockerfiles/infer.dockerfile
