name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
        pytorch-version: ['2.0.0', '2.1.0', '2.2.0']
#        exclude:
#          # Exclude older PyTorch version on Windows due to potential compatibility issues
#          - os: windows-latest
#            pytorch-version: '2.0.0'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements_dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.pytorch-version }}
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -e .

      - name: Run tests
        run: |
          coverage run -m pytest tests/
          coverage report -m
          coverage html --show-contexts --title "Coverage Report for EHR Classification"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{ matrix.os }}-py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}
          path: htmlcov/
          retention-days: 14
